
server:
  port: 8080
  servlet: 
     contextPath: /ProyectoDemo
  
spring:
  spring.main.banner-mode: off 
  jpa:
     properties.hibernate.format_sql: true 
  profiles:
    active: ambiente_desarrollo
    
---

spring:
  profiles: ambiente_desarrollo
logging:
  path: logs/dev
  file: ${logging.path}/${spring.profiles}_profile_app.log
  file.max-history: 5
  file.max-size: 10MB
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO 
    com.demo: DEBUG
    org.springframework.web: INFO
    org.hibernate: DEBUG
    org.hibernate.type: TRACE
    
---

spring:
  profiles: ambiente_productivo
logging:
  path: logs/prod
  file: ${logging.path}/${spring.profiles}_profile_app.log
  file.max-history: 2
  file.max-size: 1KB
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: WARN 
    com.demo: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    org.hibernate.type: WARN