
server:
  port: 8080
  servlet: 
     contextPath: /ProyectoDemo
  
spring:
  spring.main.banner-mode: off 
  jpa:
     properties.hibernate.format_sql: true 
  profiles:
    active: ambiente_desarrollo
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:
    
---

spring:
  profiles: ambiente_desarrollo
logging:
  path: logs/dev
  file: ${logging.path}/${spring.profiles}_profile_app.log
  file.max-history: 5
  file.max-size: 10MB
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO 
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    org.hibernate.type: TRACE
    
---

spring:
  profiles: ambiente_productivo
logging:
  path: logs/prod
  file: ${logging.path}/${spring.profiles}_profile_app.log
  file.max-history: 2
  file.max-size: 1KB
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: WARN 
    org.springframework.web: WARN
    org.hibernate: WARN